### ISSUE TITLE
Getting keys/values

### ISSUE THREAD

**Issue by codingHappiness** [sdwowk/Cmput291Project2#2]
getKey() and getValue() in FileTest currently return a string corresponding with the key/value that was to be searched for. This is operating on the assumption that our database has no duplicates. If the database does have duplicates, code will need to be modified to count the number of instances the key/value occurs, write each of those instances to the answers file (instead of within yet-to-be-written code in Main) and not bother returning any results.

**Comment by sdwowk** [comment]
Can we return a list of Strings?

**Comment by sdwowk** [comment]
Doing the list thing
