### ISSUE TITLE
Range Search?

### ISSUE THREAD

**Issue by sdwowk** [sdwowk/Cmput291Project2#4]
Dunno if it works properly. Throwing this up as a reminder

**Comment by codingHappiness** [comment]
Second conditional in InRange() function needs to be use the 'end' variable instead of 'start'.

**Comment by codingHappiness** [comment]
Not grabbing correct data... additionally, the same data seems to be stored in the array over and over again.

Check back against example in documentation to ensure that key/data pairs are being stored properly.
1

**Comment by codingHappiness** [comment]
Everything working except for the indexfile portion. We need to ensure we're searching through the table correctly / searching through the correct table. It may be worth considering rewriting its function in the event we're making a simple mistake.
